### ISSUE TITLE
sql文件

### ISSUE THREAD

**Issue by AmbitiousDesigner** [Z710210920/gms#2]
把sql文件上传一下

**Comment by Z710210920** [comment]
重要的事情说三遍：没有sql文件没有sql文件没有sql文件！那会儿还年轻根本不知道还要备份sql文件这个事儿，而且这是21年写的，项目不一定跑的起来，我也不打算改了。这个项目是照着尚硅谷的 谷粒学院（[https://www.bilibili.com/video/BV1dQ4y1A75e/?share_source=copy_web&vd_source=d902de30fa4d5a91adbe719c24ff1029）](https://www.bilibili.com/video/BV1dQ4y1A75e/?share_source=copy_web&vd_source=d902de30fa4d5a91adbe719c24ff1029%EF%BC%89) 写的，有需要请找谷粒学院

**Comment by AmbitiousDesigner** [comment]
fine thank you


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Z710210920/gms"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月6日(星期天) 晚上6:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Z710210920/gms] sql文件 (Issue #2)





 
重要的事情说三遍：没有sql文件没有sql文件没有sql文件！那会儿还年轻根本不知道还要备份sql文件这个事儿，而且这是21年写的，项目不一定跑的起来，我也不打算改了。这个项目是照着尚硅谷的 谷粒学院（https://www.bilibili.com/video/BV1dQ4y1A75e/?share_source=copy_web&amp;vd_source=d902de30fa4d5a91adbe719c24ff1029） 写的，有需要请找谷粒学院
